# Generated by Django 5.0.14 on 2026-02-05 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TEAM_INVITATION', 'Convite de Time'), ('MATCH_SCHEDULED', 'Partida Agendada'), ('MATCH_RESULT', 'Resultado de Partida'), ('MATCH_CONTESTED', 'Partida Contestada'), ('CHAMPIONSHIP_ENROLLED', 'Inscrito em Campeonato'), ('CHAMPIONSHIP_STARTED', 'Campeonato Iniciado'), ('CHAMPIONSHIP_FINISHED', 'Campeonato Finalizado'), ('SYSTEM', 'Notificação do Sistema')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL de Ação')),
                ('related_team_id', models.IntegerField(blank=True, null=True)),
                ('related_match_id', models.IntegerField(blank=True, null=True)),
                ('related_championship_id', models.IntegerField(blank=True, null=True)),
                ('related_invitation_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='fnc_notific_user_id_e2b4e3_idx'), models.Index(fields=['user', 'is_read'], name='fnc_notific_user_id_ca2150_idx')],
            },
        ),
    ]
