# Generated by Django 5.0.14 on 2026-03-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_leave_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TEAM_INVITATION', 'Convite de Time'), ('TEAM_LEAVE_REQUEST', 'Pedido de Saída de Time'), ('MATCH_SCHEDULED', 'Partida Agendada'), ('MATCH_RESULT', 'Resultado de Partida'), ('MATCH_CONTESTED', 'Partida Contestada'), ('MATCH_CALLUP', 'Convocação para Partida'), ('CHAMPIONSHIP_ENROLLED', 'Inscrito em Campeonato'), ('CHAMPIONSHIP_STARTED', 'Campeonato Iniciado'), ('CHAMPIONSHIP_FINISHED', 'Campeonato Finalizado'), ('SYSTEM', 'Notificação do Sistema')], max_length=30, verbose_name='Tipo'),
        ),
    ]
