# Generated by Django 5.0.14 on 2026-02-03 18:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fnc_championships', '0002_initial'),
        ('fnc_teams', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(help_text='Minuto em que o gol foi marcado (1-120)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='minuto')),
                ('goal_type', models.CharField(choices=[('REGULAR', 'Gol Normal'), ('PENALTY', 'Pênalti'), ('FREE_KICK', 'Falta Direta'), ('HEADER', 'Cabeçada'), ('VOLLEY', 'Voleio'), ('OWN_GOAL', 'Gol Contra')], default='REGULAR', max_length=20, verbose_name='tipo de gol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='users.playerprofile', verbose_name='autor do gol')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'gol',
                'verbose_name_plural': 'gols',
                'ordering': ['match', 'minute'],
            },
        ),
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assists_made', to='users.playerprofile', verbose_name='assistente')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assist', to='fnc_matches.goal', verbose_name='gol')),
            ],
            options={
                'verbose_name': 'assistência',
                'verbose_name_plural': 'assistências',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('FRIENDLY', 'Amistoso'), ('CHAMPIONSHIP', 'Campeonato'), ('PLAYOFF', 'Playoff'), ('FINAL', 'Final')], default='FRIENDLY', max_length=20, verbose_name='tipo de partida')),
                ('round_number', models.PositiveIntegerField(blank=True, help_text='Número da rodada no campeonato', null=True, verbose_name='rodada')),
                ('scheduled_date', models.DateTimeField(verbose_name='data agendada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='término')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='placar casa')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='placar visitante')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('IN_PROGRESS', 'Em Andamento'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada'), ('CONTESTED', 'Contestada')], default='SCHEDULED', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('away_formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_away', to='fnc_teams.formation', verbose_name='formação visitante')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='fnc_teams.team', verbose_name='time visitante')),
                ('championship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fnc_championships.championship', verbose_name='campeonato')),
                ('home_formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_home', to='fnc_teams.formation', verbose_name='formação casa')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='fnc_teams.team', verbose_name='time da casa')),
            ],
            options={
                'verbose_name': 'partida',
                'verbose_name_plural': 'partidas',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='fnc_matches.match', verbose_name='partida'),
        ),
        migrations.CreateModel(
            name='Contestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('WRONG_SCORE', 'Placar Incorreto'), ('MISSING_PLAYER', 'Jogador Ausente na Súmula'), ('FAKE_SCREENSHOT', 'Screenshot Falso'), ('OPPONENT_QUIT', 'Adversário Saiu da Partida'), ('CONNECTION_ISSUE', 'Problema de Conexão'), ('OTHER', 'Outro')], max_length=20, verbose_name='motivo')),
                ('description', models.TextField(verbose_name='descrição detalhada')),
                ('evidence', models.ImageField(blank=True, help_text='Screenshot ou foto comprovando a contestação', null=True, upload_to='contestations/', verbose_name='evidência')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('UNDER_REVIEW', 'Em Análise'), ('ACCEPTED', 'Aceita'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=20, verbose_name='status')),
                ('response', models.TextField(blank=True, verbose_name='resposta')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='analisado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('contested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestations_made', to=settings.AUTH_USER_MODEL, verbose_name='contestado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestations_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='analisado por')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestations', to='fnc_teams.team', verbose_name='time')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestations', to='fnc_matches.match', verbose_name='partida')),
            ],
            options={
                'verbose_name': 'contestação',
                'verbose_name_plural': 'contestações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('YELLOW', 'Amarelo'), ('RED', 'Vermelho')], max_length=10, verbose_name='tipo de cartão')),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='minuto')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_received', to='users.playerprofile', verbose_name='jogador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='fnc_teams.team', verbose_name='time')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='fnc_matches.match', verbose_name='partida')),
            ],
            options={
                'verbose_name': 'cartão',
                'verbose_name_plural': 'cartões',
                'ordering': ['match', 'minute'],
            },
        ),
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(help_text='Screenshot do resultado final do jogo', upload_to='match_reports/', verbose_name='print do resultado')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SUBMITTED', 'Enviada'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=20, verbose_name='status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motivo da rejeição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='fnc_matches.match', verbose_name='partida')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='reportado por')),
            ],
            options={
                'verbose_name': 'súmula',
                'verbose_name_plural': 'súmulas',
                'ordering': ['-created_at'],
            },
        ),
    ]
