# Generated by Django 5.0.14 on 2026-02-10 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_matches', '0001_initial'),
        ('fnc_teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelada em'),
        ),
        migrations.AddField(
            model_name='match',
            name='cancelled_reason',
            field=models.TextField(blank=True, verbose_name='motivo do cancelamento'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_walkover',
            field=models.BooleanField(default=False, help_text='Indica se a partida terminou por WO (time não compareceu)', verbose_name='walkover'),
        ),
        migrations.AddField(
            model_name='match',
            name='walkover_reason',
            field=models.TextField(blank=True, help_text='Explicação sobre o walk-over', verbose_name='motivo do WO'),
        ),
        migrations.AddField(
            model_name='match',
            name='walkover_team',
            field=models.ForeignKey(blank=True, help_text='Time que não compareceu e perdeu por WO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walkover_matches', to='fnc_teams.team', verbose_name='time que recebeu WO'),
        ),
    ]
