# Generated by Django 5.0.14 on 2026-02-12 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_matches', '0002_match_cancelled_at_match_cancelled_reason_and_more'),
        ('fnc_teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('DECLINED', 'Recusado')], default='PENDING', max_length=20, verbose_name='status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('decline_reason', models.TextField(blank=True, verbose_name='motivo de recusa')),
                ('confirmation_deadline', models.DateTimeField(help_text='Prazo limite para confirmar presença', verbose_name='prazo de confirmação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='fnc_matches.match', verbose_name='partida')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_confirmations', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'confirmação de partida',
                'verbose_name_plural': 'confirmações de partida',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match', 'team'], name='fnc_matches_match_i_cefec1_idx'), models.Index(fields=['team', 'status'], name='fnc_matches_team_id_cdce01_idx'), models.Index(fields=['confirmation_deadline'], name='fnc_matches_confirm_83d5c7_idx')],
                'unique_together': {('match', 'team')},
            },
        ),
        migrations.CreateModel(
            name='MatchProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateTimeField(verbose_name='data proposta')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceita'), ('REJECTED', 'Rejeitada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=20, verbose_name='status')),
                ('response_message', models.TextField(blank=True, help_text='Motivo da rejeição ou comentário', verbose_name='mensagem de resposta')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_proposals', to='fnc_matches.match', verbose_name='partida')),
                ('proposed_by_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_proposals', to='fnc_teams.team', verbose_name='proposto por')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_proposal_responses', to=settings.AUTH_USER_MODEL, verbose_name='respondido por')),
            ],
            options={
                'verbose_name': 'proposta de data',
                'verbose_name_plural': 'propostas de data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match', 'status'], name='fnc_matches_match_i_2b4ec4_idx'), models.Index(fields=['proposed_by_team', 'status'], name='fnc_matches_propose_a0907a_idx')],
            },
        ),
    ]
