# Generated by Django 5.0.14 on 2026-02-12 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_championships', '0004_championship_current_phase_and_more'),
        ('fnc_matches', '0003_matchconfirmation_matchproposal'),
        ('fnc_teams', '0002_initial'),
        ('users', '0003_alter_user_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('PLAYER', 'Jogador'), ('TEAM', 'Time')], max_length=20, verbose_name='tipo de alvo')),
                ('penalty_type', models.CharField(choices=[('WARNING', 'Advertência'), ('YELLOW_CARD', 'Cartão Amarelo'), ('RED_CARD', 'Cartão Vermelho'), ('WALKOVER', 'Walk-Over'), ('UNSPORTSMANLIKE', 'Conduta Antidesportiva'), ('NO_SHOW', 'Não Comparecimento'), ('RULES_VIOLATION', 'Violação de Regras'), ('OTHER', 'Outro')], max_length=20, verbose_name='tipo de penalidade')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('games_suspended', models.PositiveIntegerField(default=0, help_text='Número de jogos que o jogador/time ficará suspenso', verbose_name='jogos de suspensão')),
                ('games_served', models.PositiveIntegerField(default=0, help_text='Número de jogos já cumpridos da suspensão', verbose_name='jogos cumpridos')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, help_text='Valor em reais da multa aplicada', max_digits=10, verbose_name='valor da multa')),
                ('fine_paid', models.BooleanField(default=False, verbose_name='multa paga')),
                ('points_deducted', models.IntegerField(default=0, help_text='Pontos deduzidos da classificação', verbose_name='pontos deduzidos')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('SERVED', 'Cumprida'), ('APPEALED', 'Em Recurso'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='aplicado em')),
                ('appeal_reason', models.TextField(blank=True, verbose_name='motivo do recurso')),
                ('appeal_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='recurso enviado em')),
                ('appeal_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='recurso analisado em')),
                ('appeal_decision', models.TextField(blank=True, verbose_name='decisão do recurso')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('appeal_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_appeals_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='recurso analisado por')),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_applied', to=settings.AUTH_USER_MODEL, verbose_name='aplicado por')),
                ('championship', models.ForeignKey(help_text='Campeonato onde a penalidade se aplica', on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='fnc_championships.championship', verbose_name='campeonato')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='fnc_matches.match', verbose_name='partida')),
                ('player', models.ForeignKey(blank=True, help_text='Preenchido se penalidade for para jogador', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='users.playerprofile', verbose_name='jogador')),
                ('team', models.ForeignKey(blank=True, help_text='Preenchido se penalidade for para time', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'penalidade',
                'verbose_name_plural': 'penalidades',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='argumentação')),
                ('evidence', models.FileField(blank=True, help_text='Documento ou imagem como evidência', null=True, upload_to='penalty_appeals/', verbose_name='evidência')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('UNDER_REVIEW', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='analisado em')),
                ('decision', models.TextField(blank=True, verbose_name='decisão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='fnc_matches.penalty', verbose_name='penalidade')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='analisado por')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_appeals_submitted', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
            ],
            options={
                'verbose_name': 'recurso de penalidade',
                'verbose_name_plural': 'recursos de penalidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['target_type', 'player'], name='fnc_matches_target__74a428_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['target_type', 'team'], name='fnc_matches_target__68e771_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['championship', 'status'], name='fnc_matches_champio_87b93a_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['penalty_type', 'status'], name='fnc_matches_penalty_eba95e_idx'),
        ),
    ]
