# Generated by Django 5.0.14 on 2026-03-09 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_matches', '0004_penalty_penaltyappeal_and_more'),
        ('fnc_teams', '0002_initial'),
        ('users', '0003_alter_user_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(choices=[('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('4-4-2', '4-4-2'), ('5-3-2', '5-3-2'), ('4-3-2-1', '4-3-2-1'), ('4-1-2-1-2', '4-1-2-1-2'), ('4-3-3(4)', '4-3-3(4)')], max_length=20, verbose_name='formação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='fnc_matches.match', verbose_name='partida')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_lineups', to=settings.AUTH_USER_MODEL, verbose_name='submetido por')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_lineups', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'escalação da partida',
                'verbose_name_plural': 'escalações das partidas',
                'ordering': ['-created_at'],
                'unique_together': {('match', 'team')},
            },
        ),
        migrations.CreateModel(
            name='MatchLineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10, verbose_name='posição')),
                ('x_position', models.FloatField(verbose_name='posição X (%)')),
                ('y_position', models.FloatField(verbose_name='posição Y (%)')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fnc_matches.matchlineup', verbose_name='escalação')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_appearances', to='users.playerprofile', verbose_name='jogador')),
            ],
            options={
                'verbose_name': 'jogador na escalação',
                'verbose_name_plural': 'jogadores na escalação',
                'unique_together': {('lineup', 'player')},
            },
        ),
    ]
