# Generated by Django 5.0.14 on 2026-04-02 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_matches', '0006_remove_penalty_penaltyappeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='minute',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='minuto'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='minute',
            field=models.PositiveIntegerField(blank=True, help_text='Minuto em que o gol foi marcado (1-120). Nulo quando importado da EA API.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='minuto'),
        ),
    ]
