# Generated by Django 5.0.14 on 2026-04-29 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_matches', '0008_alter_match_options'),
        ('fnc_teams', '0004_team_lineup_visual_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contestation',
            name='decided_away_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='placar visitante decidido'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='decided_home_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='placar casa decidido'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='decided_winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestations_as_decided_winner', to='fnc_teams.team', verbose_name='vencedor decidido'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='decision_reason',
            field=models.TextField(blank=True, verbose_name='motivo da decisão'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='decision_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='snapshot da decisão'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='decision_type',
            field=models.CharField(blank=True, choices=[('APPROVE_CURRENT_RESULT', 'Aprovar resultado atual'), ('CHANGE_RESULT', 'Alterar resultado')], max_length=40, verbose_name='tipo de decisão'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='previous_away_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='placar visitante anterior'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='previous_home_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='placar casa anterior'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='previous_winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestations_as_previous_winner', to='fnc_teams.team', verbose_name='vencedor anterior'),
        ),
        migrations.CreateModel(
            name='ContestationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Contestação criada'), ('UNDER_REVIEW', 'Contestação em análise'), ('APPROVE_CURRENT_RESULT', 'Resultado atual aprovado'), ('CHANGE_RESULT', 'Resultado alterado')], max_length=40, verbose_name='ação')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('previous_result', models.JSONField(blank=True, default=dict, verbose_name='resultado anterior')),
                ('new_result', models.JSONField(blank=True, default=dict, verbose_name='novo resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('contestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='fnc_matches.contestation', verbose_name='contestação')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestation_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='executado por')),
            ],
            options={
                'verbose_name': 'auditoria de contestação',
                'verbose_name_plural': 'auditorias de contestações',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
