# Generated by Django 5.0.14 on 2026-06-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_matches', '0010_match_irregularity_confirmation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='source',
            field=models.CharField(choices=[('EA', 'EA API'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10, verbose_name='origem'),
        ),
        migrations.AddField(
            model_name='goal',
            name='source',
            field=models.CharField(choices=[('EA', 'EA API'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10, verbose_name='origem'),
        ),
    ]
