# Generated by Django 5.0.14 on 2026-02-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.JSONField(help_text='Estrutura do chaveamento em JSON', verbose_name='estrutura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'chaveamento',
                'verbose_name_plural': 'chaveamentos',
            },
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrição')),
                ('rules', models.TextField(verbose_name='regras')),
                ('championship_type', models.CharField(choices=[('KNOCKOUT', 'Mata-Mata'), ('LEAGUE', 'Pontos Corridos')], max_length=20, verbose_name='tipo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='championship_banners/', verbose_name='banner')),
                ('enrollment_start', models.DateTimeField(verbose_name='início das inscrições')),
                ('enrollment_end', models.DateTimeField(verbose_name='fim das inscrições')),
                ('start_date', models.DateTimeField(verbose_name='data de início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='data de término')),
                ('enrollment_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='taxa de inscrição')),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='premiação total')),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True, verbose_name='máximo de times')),
                ('min_teams', models.PositiveIntegerField(default=4, verbose_name='mínimo de times')),
                ('number_of_winners', models.PositiveIntegerField(default=1, verbose_name='número de ganhadores')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('OPEN', 'Inscrições Abertas'), ('IN_PROGRESS', 'Em Andamento'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'campeonato',
                'verbose_name_plural': 'campeonatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='status')),
                ('payment_status', models.CharField(default='PENDING', max_length=20, verbose_name='status do pagamento')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do pagamento')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='inscrito em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
            ],
            options={
                'verbose_name': 'inscrição',
                'verbose_name_plural': 'inscrições',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='posição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'premiação',
                'verbose_name_plural': 'premiações',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='jogos')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='vitórias')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='empates')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='derrotas')),
                ('goals_for', models.PositiveIntegerField(default=0, verbose_name='gols pró')),
                ('goals_against', models.PositiveIntegerField(default=0, verbose_name='gols contra')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='pontos')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'classificação',
                'verbose_name_plural': 'classificações',
                'ordering': ['-points', '-wins', '-goals_for'],
            },
        ),
    ]
