# Generated by Django 5.0.14 on 2026-02-03 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fnc_championships', '0001_initial'),
        ('fnc_teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_championships', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='championship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='fnc_championships.championship', verbose_name='campeonato'),
        ),
        migrations.AddField(
            model_name='championshipenrollment',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='fnc_championships.championship', verbose_name='campeonato'),
        ),
        migrations.AddField(
            model_name='championshipenrollment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='fnc_teams.team', verbose_name='time'),
        ),
        migrations.AddField(
            model_name='championshipprize',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='fnc_championships.championship', verbose_name='campeonato'),
        ),
        migrations.AddField(
            model_name='championshipprize',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes_won', to='fnc_teams.team', verbose_name='time vencedor'),
        ),
        migrations.AddField(
            model_name='standings',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='fnc_championships.championship', verbose_name='campeonato'),
        ),
        migrations.AddField(
            model_name='standings',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnc_teams.team', verbose_name='time'),
        ),
        migrations.AlterUniqueTogether(
            name='championshipenrollment',
            unique_together={('championship', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='championshipprize',
            unique_together={('championship', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='standings',
            unique_together={('championship', 'team')},
        ),
    ]
