# Generated by Django 5.0.14 on 2026-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_championships', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo quadrada do campeonato (recomendado: 512x512px)', null=True, upload_to='championship_logos/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner do campeonato (recomendado: 1600x500px)', null=True, upload_to='championship_banners/', verbose_name='banner'),
        ),
    ]
