# Generated by Django 5.0.14 on 2026-02-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_championships', '0003_championship_logo_alter_championship_banner'),
        ('fnc_teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='current_phase',
            field=models.CharField(blank=True, choices=[('GROUPS', 'Fase de Grupos'), ('KNOCKOUT', 'Fase Eliminatória'), ('FINISHED', 'Finalizado')], max_length=20, null=True, verbose_name='fase atual'),
        ),
        migrations.AddField(
            model_name='championship',
            name='has_third_place_match',
            field=models.BooleanField(default=False, verbose_name='disputa de 3º lugar'),
        ),
        migrations.AddField(
            model_name='championship',
            name='num_groups',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2 Grupos'), (4, '4 Grupos'), (8, '8 Grupos')], help_text='Apenas para campeonatos Grupos + Mata-Mata', null=True, verbose_name='número de grupos'),
        ),
        migrations.AddField(
            model_name='championship',
            name='qualified_per_group',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True, verbose_name='classificados por grupo'),
        ),
        migrations.AddField(
            model_name='championship',
            name='teams_per_group',
            field=models.PositiveSmallIntegerField(blank=True, default=4, null=True, verbose_name='times por grupo'),
        ),
        migrations.AddField(
            model_name='championship',
            name='tiebreak_criteria',
            field=models.JSONField(blank=True, default=list, help_text='Ordem de critérios: wins, goal_diff, goals_for', verbose_name='critérios de desempate'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='championship_type',
            field=models.CharField(choices=[('KNOCKOUT', 'Mata-Mata'), ('LEAGUE', 'Pontos Corridos'), ('GROUPS_KNOCKOUT', 'Grupos + Mata-Mata')], max_length=20, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='fnc_championships.championship', verbose_name='campeonato')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['order'],
                'unique_together': {('championship', 'order')},
            },
        ),
        migrations.CreateModel(
            name='GroupStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='jogos')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='vitórias')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='empates')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='derrotas')),
                ('goals_for', models.PositiveIntegerField(default=0, verbose_name='gols pró')),
                ('goals_against', models.PositiveIntegerField(default=0, verbose_name='gols contra')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='pontos')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='posição')),
                ('qualified', models.BooleanField(default=False, verbose_name='classificado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='fnc_championships.group', verbose_name='grupo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'classificação de grupo',
                'verbose_name_plural': 'classificações de grupo',
                'ordering': ['group__order', '-points', '-wins', '-goals_for'],
                'unique_together': {('group', 'team')},
            },
        ),
    ]
