# Generated by Django 5.0.14 on 2026-03-24 15:41

from django.db import migrations, models


def migrate_enrollment_statuses(apps, schema_editor):
    ChampionshipEnrollment = apps.get_model('fnc_championships', 'ChampionshipEnrollment')
    ChampionshipEnrollment.objects.filter(status='PENDING').update(status='PENDING_PAYMENT')
    ChampionshipEnrollment.objects.filter(payment_status='COMPLETED').update(payment_status='PAID')


def reverse_enrollment_statuses(apps, schema_editor):
    ChampionshipEnrollment = apps.get_model('fnc_championships', 'ChampionshipEnrollment')
    ChampionshipEnrollment.objects.filter(status='PENDING_PAYMENT').update(status='PENDING')
    ChampionshipEnrollment.objects.filter(payment_status='PAID').update(payment_status='COMPLETED')


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_championships', '0004_championship_current_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championshipenrollment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('FAILED', 'Falhou'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20, verbose_name='status do pagamento'),
        ),
        migrations.AlterField(
            model_name='championshipenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Aguardando Pagamento'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('CANCELLED', 'Cancelado')], default='PENDING_PAYMENT', max_length=20, verbose_name='status'),
        ),
        migrations.RunPython(migrate_enrollment_statuses, reverse_enrollment_statuses),
    ]
