# Generated by Django 5.0.14 on 2026-03-25 20:09

from django.db import migrations, models


def migrate_championship_statuses(apps, schema_editor):
    Championship = apps.get_model('fnc_championships', 'Championship')
    from django.utils import timezone

    now = timezone.now()

    for championship in Championship.objects.exclude(status='CANCELLED'):
        if championship.end_date and now >= championship.end_date:
            championship.status = 'FINISHED'
        elif now >= championship.start_date:
            championship.status = 'IN_PROGRESS'
        elif championship.enrollment_start <= now <= championship.enrollment_end:
            championship.status = 'OPEN'
        else:
            championship.status = 'SCHEDULED'
        championship.save(update_fields=['status'])


def reverse_championship_statuses(apps, schema_editor):
    Championship = apps.get_model('fnc_championships', 'Championship')
    Championship.objects.filter(status='SCHEDULED').update(status='DRAFT')


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_championships', '0005_alter_championshipenrollment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Programado'), ('OPEN', 'Inscrições Abertas'), ('IN_PROGRESS', 'Em Andamento'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20, verbose_name='status'),
        ),
        migrations.RunPython(migrate_championship_statuses, reverse_championship_statuses),
    ]
