# Generated by Django 5.0.14 on 2026-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_championships', '0006_alter_championship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='game_days',
            field=models.JSONField(blank=True, default=list, help_text='Lista de códigos de dia: MON, TUE, WED, THU, FRI, SAT, SUN', verbose_name='dias de jogo'),
        ),
        migrations.AddField(
            model_name='championship',
            name='game_end_time',
            field=models.TimeField(blank=True, help_text='Horário de término da janela de jogos (ex: 23:00)', null=True, verbose_name='horário de término dos jogos'),
        ),
        migrations.AddField(
            model_name='championship',
            name='game_start_time',
            field=models.TimeField(blank=True, help_text='Horário de início da janela de jogos (ex: 20:00)', null=True, verbose_name='horário de início dos jogos'),
        ),
    ]
