# Generated by Django 5.0.14 on 2026-05-06 14:13

from django.db import migrations, models


def migrate_scheduled_to_pending(apps, schema_editor):
    Championship = apps.get_model('fnc_championships', 'Championship')
    Championship.objects.filter(status='SCHEDULED').update(status='PENDING')


def reverse_pending_to_scheduled(apps, schema_editor):
    Championship = apps.get_model('fnc_championships', 'Championship')
    Championship.objects.filter(status='PENDING').update(status='SCHEDULED')


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_championships', '0007_add_game_schedule_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_scheduled_to_pending, reverse_pending_to_scheduled),
        migrations.AlterField(
            model_name='championship',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de início'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('OPEN', 'Inscrições Abertas'), ('IN_PROGRESS', 'Em Andamento'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
