# Generated by Django 5.0.14 on 2026-02-03 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fnc_championships', '0002_initial'),
        ('fnc_teams', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='partidas jogadas')),
                ('matches_won', models.PositiveIntegerField(default=0, verbose_name='vitórias')),
                ('matches_drawn', models.PositiveIntegerField(default=0, verbose_name='empates')),
                ('matches_lost', models.PositiveIntegerField(default=0, verbose_name='derrotas')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='gols')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='assistências')),
                ('yellow_cards', models.PositiveIntegerField(default=0, verbose_name='cartões amarelos')),
                ('red_cards', models.PositiveIntegerField(default=0, verbose_name='cartões vermelhos')),
                ('minutes_played', models.PositiveIntegerField(default=0, verbose_name='minutos jogados')),
                ('clean_sheets', models.PositiveIntegerField(default=0, help_text='Apenas para goleiros', verbose_name='jogos sem sofrer gols')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Nota média do jogador (0-10)', max_digits=3, verbose_name='nota média')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='fnc_championships.championship', verbose_name='campeonato')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='users.playerprofile', verbose_name='jogador')),
                ('team', models.ForeignKey(help_text='Time pelo qual o jogador estava jogando', on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'estatística do jogador',
                'verbose_name_plural': 'estatísticas dos jogadores',
                'ordering': ['-goals', '-assists'],
                'unique_together': {('player', 'championship', 'team')},
            },
        ),
        migrations.CreateModel(
            name='SeasonSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveIntegerField(help_text='Ano da temporada (ex: 2024)', verbose_name='ano da temporada')),
                ('total_matches', models.PositiveIntegerField(default=0, verbose_name='partidas totais')),
                ('total_wins', models.PositiveIntegerField(default=0, verbose_name='vitórias totais')),
                ('total_draws', models.PositiveIntegerField(default=0, verbose_name='empates totais')),
                ('total_losses', models.PositiveIntegerField(default=0, verbose_name='derrotas totais')),
                ('total_goals', models.PositiveIntegerField(default=0, verbose_name='gols totais')),
                ('total_assists', models.PositiveIntegerField(default=0, verbose_name='assistências totais')),
                ('total_yellow_cards', models.PositiveIntegerField(default=0, verbose_name='cartões amarelos totais')),
                ('total_red_cards', models.PositiveIntegerField(default=0, verbose_name='cartões vermelhos totais')),
                ('championships_won', models.PositiveIntegerField(default=0, verbose_name='campeonatos vencidos')),
                ('runner_up_finishes', models.PositiveIntegerField(default=0, verbose_name='vice-campeonatos')),
                ('golden_boot', models.BooleanField(default=False, verbose_name='artilheiro')),
                ('best_player', models.BooleanField(default=False, verbose_name='melhor jogador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='season_summary', to='users.playerprofile', verbose_name='jogador')),
            ],
            options={
                'verbose_name': 'resumo da temporada',
                'verbose_name_plural': 'resumos das temporadas',
                'ordering': ['-season_year'],
                'unique_together': {('player', 'season_year')},
            },
        ),
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='partidas jogadas')),
                ('matches_won', models.PositiveIntegerField(default=0, verbose_name='vitórias')),
                ('matches_drawn', models.PositiveIntegerField(default=0, verbose_name='empates')),
                ('matches_lost', models.PositiveIntegerField(default=0, verbose_name='derrotas')),
                ('goals_scored', models.PositiveIntegerField(default=0, verbose_name='gols marcados')),
                ('goals_conceded', models.PositiveIntegerField(default=0, verbose_name='gols sofridos')),
                ('yellow_cards', models.PositiveIntegerField(default=0, verbose_name='cartões amarelos')),
                ('red_cards', models.PositiveIntegerField(default=0, verbose_name='cartões vermelhos')),
                ('clean_sheets', models.PositiveIntegerField(default=0, verbose_name='jogos sem sofrer gols')),
                ('biggest_win_margin', models.PositiveIntegerField(default=0, verbose_name='maior goleada')),
                ('biggest_loss_margin', models.PositiveIntegerField(default=0, verbose_name='maior derrota')),
                ('current_win_streak', models.PositiveIntegerField(default=0, verbose_name='sequência de vitórias atual')),
                ('longest_win_streak', models.PositiveIntegerField(default=0, verbose_name='maior sequência de vitórias')),
                ('current_unbeaten_streak', models.PositiveIntegerField(default=0, verbose_name='sequência sem perder atual')),
                ('longest_unbeaten_streak', models.PositiveIntegerField(default=0, verbose_name='maior sequência sem perder')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_statistics', to='fnc_championships.championship', verbose_name='campeonato')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'estatística do time',
                'verbose_name_plural': 'estatísticas dos times',
                'ordering': ['-matches_won', '-goals_scored'],
                'unique_together': {('team', 'championship')},
            },
        ),
        migrations.CreateModel(
            name='TopScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='gols')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='assistências')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='partidas jogadas')),
                ('position', models.PositiveIntegerField(help_text='Posição no ranking de artilheiros', verbose_name='posição')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_scorers', to='fnc_championships.championship', verbose_name='campeonato')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_scorer_awards', to='users.playerprofile', verbose_name='jogador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'artilheiro',
                'verbose_name_plural': 'artilheiros',
                'ordering': ['championship', 'position'],
                'unique_together': {('championship', 'player')},
            },
        ),
    ]
