# Generated by Django 5.0.14 on 2026-04-13 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_championships', '0007_add_game_schedule_fields'),
        ('fnc_matches', '0007_allow_null_minute_goal_card'),
        ('fnc_teams', '0003_add_teamleaverequest'),
        ('player_stats', '0001_initial'),
        ('users', '0005_add_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPerformanceMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('championship', 'Campeonato'), ('friendly', 'Amistoso')], max_length=20, verbose_name='contexto')),
                ('is_home', models.BooleanField(default=False, verbose_name='jogou em casa')),
                ('played_at', models.DateTimeField(verbose_name='jogada em')),
                ('opponent_name', models.CharField(max_length=200, verbose_name='nome do adversário')),
                ('goals_scored', models.PositiveIntegerField(default=0, verbose_name='gols marcados')),
                ('goals_conceded', models.PositiveIntegerField(default=0, verbose_name='gols sofridos')),
                ('result', models.CharField(choices=[('W', 'Vitória'), ('D', 'Empate'), ('L', 'Derrota')], max_length=1, verbose_name='resultado')),
                ('clean_sheet', models.BooleanField(default=False, verbose_name='clean sheet')),
                ('has_advanced_data', models.BooleanField(default=False, verbose_name='tem dados avançados')),
                ('advanced_players', models.PositiveIntegerField(default=0, verbose_name='jogadores com dados avançados')),
                ('lineup_players', models.PositiveIntegerField(default=0, verbose_name='jogadores escalados')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota média')),
                ('passes_made', models.PositiveIntegerField(default=0, verbose_name='passes certos')),
                ('pass_attempts', models.PositiveIntegerField(default=0, verbose_name='passes tentados')),
                ('tackles_made', models.PositiveIntegerField(default=0, verbose_name='desarmes certos')),
                ('tackle_attempts', models.PositiveIntegerField(default=0, verbose_name='desarmes tentados')),
                ('saves', models.PositiveIntegerField(default=0, verbose_name='defesas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('championship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_performance_matches', to='fnc_championships.championship', verbose_name='campeonato')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_performance_snapshots', to='fnc_matches.match', verbose_name='partida')),
                ('opponent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_performance_matches', to='fnc_teams.team', verbose_name='adversário')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_matches', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'desempenho do time por partida',
                'verbose_name_plural': 'desempenhos do time por partida',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamPlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name_snapshot', models.CharField(max_length=200, verbose_name='nome do jogador')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='posição')),
                ('has_advanced_data', models.BooleanField(default=False, verbose_name='tem dados avançados')),
                ('matches_played', models.PositiveIntegerField(default=1, verbose_name='partidas consideradas')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='gols')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='assistências')),
                ('passes_made', models.PositiveIntegerField(default=0, verbose_name='passes certos')),
                ('pass_attempts', models.PositiveIntegerField(default=0, verbose_name='passes tentados')),
                ('shots', models.PositiveIntegerField(default=0, verbose_name='finalizações')),
                ('tackles_made', models.PositiveIntegerField(default=0, verbose_name='desarmes certos')),
                ('tackle_attempts', models.PositiveIntegerField(default=0, verbose_name='desarmes tentados')),
                ('saves', models.PositiveIntegerField(default=0, verbose_name='defesas')),
                ('seconds_played', models.PositiveIntegerField(default=0, verbose_name='segundos jogados')),
                ('cards', models.PositiveIntegerField(default=0, verbose_name='cartões')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('championship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_performance_matches', to='fnc_championships.championship', verbose_name='campeonato')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_performance_snapshots', to='fnc_matches.match', verbose_name='partida')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_performance_matches', to='users.playerprofile', verbose_name='jogador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_performance_matches', to='fnc_teams.team', verbose_name='time')),
                ('team_performance_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='player_stats.teamperformancematch', verbose_name='snapshot do time')),
            ],
            options={
                'verbose_name': 'desempenho do jogador por partida',
                'verbose_name_plural': 'desempenhos dos jogadores por partida',
                'ordering': ['-match__scheduled_date', 'player_name_snapshot'],
            },
        ),
        migrations.AddConstraint(
            model_name='teamperformancematch',
            constraint=models.UniqueConstraint(fields=('team', 'match'), name='unique_team_performance_match'),
        ),
        migrations.AddConstraint(
            model_name='teamplayerperformance',
            constraint=models.UniqueConstraint(fields=('team', 'match', 'player_name_snapshot'), name='unique_team_player_performance_match'),
        ),
    ]
