# Generated by Django 5.0.14 on 2026-05-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_matches', '0007_allow_null_minute_goal_card'),
        ('fnc_teams', '0003_add_teamleaverequest'),
        ('player_stats', '0002_teamperformancematch_teamplayerperformance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTeamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='pontos totais')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='partidas jogadas')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='vitórias')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='empates')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='derrotas')),
                ('goals_for', models.PositiveIntegerField(default=0, verbose_name='gols marcados')),
                ('goals_against', models.PositiveIntegerField(default=0, verbose_name='gols sofridos')),
                ('goal_difference', models.IntegerField(default=0, verbose_name='saldo de gols')),
                ('tier', models.CharField(choices=[('TIER_1', 'Tier 1'), ('TIER_2', 'Tier 2'), ('TIER_3', 'Tier 3')], default='TIER_3', max_length=10, verbose_name='tier')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_ranking', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'ranking geral do time',
                'verbose_name_plural': 'ranking geral dos times',
                'ordering': ['-total_points', '-wins', '-goal_difference', 'losses', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalTeamRankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('WIN', 'Vitória'), ('DRAW', 'Empate'), ('LOSS', 'Derrota')], max_length=10, verbose_name='resultado')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='pontos concedidos')),
                ('goals_for', models.PositiveIntegerField(default=0, verbose_name='gols marcados')),
                ('goals_against', models.PositiveIntegerField(default=0, verbose_name='gols sofridos')),
                ('counted', models.BooleanField(default=True, verbose_name='contabilizado no ranking')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_ranking_entries', to='fnc_matches.match', verbose_name='partida')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_ranking_entries', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'entrada de ranking global',
                'verbose_name_plural': 'entradas de ranking global',
                'ordering': ['-match__finished_at', '-match_id', 'team__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='globalteamrankingentry',
            constraint=models.UniqueConstraint(fields=('match', 'team'), name='unique_global_ranking_entry_match_team'),
        ),
    ]
