# Generated by Django 5.0.14 on 2026-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_stats', '0004_rankingcycle_playertierstate_tierpromotionaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertierstate',
            name='is_provisional',
            field=models.BooleanField(default=False, verbose_name='provisório'),
        ),
        migrations.AddField(
            model_name='playertierstate',
            name='position_group',
            field=models.CharField(blank=True, choices=[('GK', 'Goleiro'), ('DEF', 'Defesa'), ('MID', 'Meio'), ('ATT', 'Ataque')], max_length=3, verbose_name='grupo de posição'),
        ),
        migrations.AddField(
            model_name='playertierstate',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='detalhamento do score'),
        ),
        migrations.AlterField(
            model_name='playertierstate',
            name='promoted_to_tier',
            field=models.CharField(blank=True, choices=[('BRONZE', 'Bronze'), ('SILVER', 'Prata'), ('GOLD', 'Ouro'), ('PLATINUM', 'Platina'), ('DIAMOND', 'Diamante'), ('ELITE', 'Elite')], max_length=10, verbose_name='promovido para rank'),
        ),
        migrations.AlterField(
            model_name='playertierstate',
            name='tier',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Prata'), ('GOLD', 'Ouro'), ('PLATINUM', 'Platina'), ('DIAMOND', 'Diamante'), ('ELITE', 'Elite')], default='BRONZE', max_length=10, verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='tierpromotionaudit',
            name='from_tier',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Prata'), ('GOLD', 'Ouro'), ('PLATINUM', 'Platina'), ('DIAMOND', 'Diamante'), ('ELITE', 'Elite')], max_length=10, verbose_name='rank anterior'),
        ),
        migrations.AlterField(
            model_name='tierpromotionaudit',
            name='to_tier',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Prata'), ('GOLD', 'Ouro'), ('PLATINUM', 'Platina'), ('DIAMOND', 'Diamante'), ('ELITE', 'Elite')], max_length=10, verbose_name='novo rank'),
        ),
    ]
