# Generated by Django 5.0.14 on 2026-04-01 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fnc_teams', '0003_add_teamleaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ea_club_id', models.CharField(help_text='Identificador único do clube na API da EA', max_length=50, verbose_name='ID do clube na EA')),
                ('platform', models.CharField(choices=[('common-gen5', 'PS5 / Xbox Series / Cross-play'), ('common-gen4', 'PS4 / Xbox One'), ('pc', 'PC')], default='common-gen5', max_length=20, verbose_name='plataforma')),
                ('name', models.CharField(help_text='Nome do clube conforme retornado pela API da EA', max_length=200, verbose_name='nome do clube')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, o clube não será incluído no polling automático', verbose_name='sincronização ativa')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='última sincronização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('team', models.OneToOneField(blank=True, help_text='Time do IMPERIUM vinculado a este clube EA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ea_club', to='fnc_teams.team', verbose_name='time interno')),
            ],
            options={
                'verbose_name': 'clube EA',
                'verbose_name_plural': 'clubes EA',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EAMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ea_match_id', models.CharField(help_text='matchId retornado pela API da EA', max_length=50, unique=True, verbose_name='ID da partida na EA')),
                ('match_type', models.CharField(choices=[('friendlyMatch', 'Amistoso'), ('leagueMatch', 'Liga Online'), ('playoffMatch', 'Playoff')], default='leagueMatch', max_length=20, verbose_name='tipo de partida')),
                ('played_at', models.DateTimeField(help_text='Timestamp da partida na EA (convertido de epoch)', verbose_name='jogada em')),
                ('home_club_name', models.CharField(help_text='Nome do clube no momento da partida (snapshot)', max_length=200, verbose_name='nome clube casa')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='placar casa')),
                ('away_club_name', models.CharField(help_text='Nome do clube no momento da partida (snapshot)', max_length=200, verbose_name='nome clube visitante')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='placar visitante')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='JSON completo retornado pela EA para esta partida', verbose_name='dados brutos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_ea_matches', to='ea_integration.eaclub', verbose_name='clube visitante')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_ea_matches', to='ea_integration.eaclub', verbose_name='clube da casa')),
            ],
            options={
                'verbose_name': 'partida EA',
                'verbose_name_plural': 'partidas EA',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='EAPlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(help_text='Gamertag/PSN ID do jogador conforme retornado pela EA', max_length=200, verbose_name='nome do jogador')),
                ('position', models.CharField(blank=True, help_text='Posição em campo (ex: GK, CB, ST, CAM)', max_length=10, verbose_name='posição')),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Nota do jogador na partida (ex: 7.50)', max_digits=4, verbose_name='nota')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='gols')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='assistências')),
                ('passes_made', models.PositiveIntegerField(default=0, verbose_name='passes certos')),
                ('pass_attempts', models.PositiveIntegerField(default=0, verbose_name='passes tentados')),
                ('shots', models.PositiveIntegerField(default=0, verbose_name='finalizações')),
                ('tackles_made', models.PositiveIntegerField(default=0, verbose_name='desarmes certos')),
                ('tackle_attempts', models.PositiveIntegerField(default=0, verbose_name='desarmes tentados')),
                ('saves', models.PositiveIntegerField(default=0, verbose_name='defesas')),
                ('red_cards', models.PositiveIntegerField(default=0, verbose_name='cartões vermelhos')),
                ('seconds_played', models.PositiveIntegerField(default=0, verbose_name='segundos jogados')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='vitória')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='derrota')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='dados brutos do jogador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('ea_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_stats', to='ea_integration.eaclub', verbose_name='clube EA')),
                ('ea_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='ea_integration.eamatch', verbose_name='partida EA')),
            ],
            options={
                'verbose_name': 'estatística de jogador EA',
                'verbose_name_plural': 'estatísticas de jogadores EA',
                'ordering': ['-rating'],
            },
        ),
        migrations.AddConstraint(
            model_name='eaclub',
            constraint=models.UniqueConstraint(fields=('ea_club_id', 'platform'), name='unique_ea_club_per_platform'),
        ),
        migrations.AddIndex(
            model_name='eamatch',
            index=models.Index(fields=['home_club', '-played_at'], name='ea_integrat_home_cl_2662c5_idx'),
        ),
        migrations.AddIndex(
            model_name='eamatch',
            index=models.Index(fields=['away_club', '-played_at'], name='ea_integrat_away_cl_efa2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='eamatch',
            index=models.Index(fields=['-played_at'], name='ea_integrat_played__230a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='eaplayermatchstats',
            index=models.Index(fields=['player_name'], name='ea_integrat_player__1951ac_idx'),
        ),
        migrations.AddIndex(
            model_name='eaplayermatchstats',
            index=models.Index(fields=['ea_club', '-created_at'], name='ea_integrat_ea_club_84cad3_idx'),
        ),
        migrations.AddConstraint(
            model_name='eaplayermatchstats',
            constraint=models.UniqueConstraint(fields=('ea_match', 'player_name', 'ea_club'), name='unique_player_per_match_per_club'),
        ),
    ]
