# Generated by Django 5.0.14 on 2026-04-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea_integration', '0001_initial'),
        ('fnc_matches', '0006_remove_penalty_penaltyappeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_type', models.CharField(choices=[('team_name_mismatch', 'Nome do time divergente'), ('team_not_registered', 'Time não cadastrado no sistema'), ('player_not_in_roster', 'Jogador não pertence ao elenco'), ('gamertag_mismatch', 'Gamertag irregular ou divergente'), ('stats_anomaly', 'Estatísticas incompatíveis'), ('incomplete_data', 'Dados incompletos na partida'), ('unexpected_team', 'Time inesperado (não era o adversário esperado)'), ('score_mismatch', 'Placar não confere com soma de gols dos jogadores'), ('no_matching_fixture', 'Nenhuma partida agendada encontrada')], max_length=30, verbose_name='tipo de validação')),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='warning', max_length=10, verbose_name='severidade')),
                ('details', models.TextField(help_text='Descrição legível da inconsistência encontrada', verbose_name='detalhes')),
                ('raw_comparison', models.JSONField(blank=True, default=dict, help_text='Dados esperados vs. encontrados. Ex: {"expected": "MVL ES", "found": "MVL_ES", "similarity": 0.92}', verbose_name='comparação de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'log de validação',
                'verbose_name_plural': 'logs de validação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='eamatch',
            name='linked_match',
            field=models.OneToOneField(blank=True, help_text='Match do campeonato IMPERIUM vinculado a esta partida EA. Preenchido automaticamente quando o sistema detecta correspondência.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ea_match', to='fnc_matches.match', verbose_name='partida interna vinculada'),
        ),
        migrations.AddField(
            model_name='eamatch',
            name='source',
            field=models.CharField(choices=[('ea_api', 'API da EA (automático)'), ('manual', 'Inserção manual')], default='ea_api', help_text='Como esta partida foi registrada no sistema', max_length=10, verbose_name='origem dos dados'),
        ),
        migrations.AddField(
            model_name='eamatch',
            name='validation_notes',
            field=models.JSONField(blank=True, default=list, help_text='Lista de inconsistências detectadas pelo sistema de validação. Ex: [{"type": "PLAYER_NOT_IN_ROSTER", "detail": "..."}]', verbose_name='notas de validação'),
        ),
        migrations.AddField(
            model_name='eamatch',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pendente de validação'), ('validated', 'Validada'), ('contested', 'Contestada — inconsistências detectadas'), ('rejected', 'Rejeitada')], db_index=True, default='pending', help_text='Resultado da validação automática', max_length=15, verbose_name='status de validação'),
        ),
        migrations.AlterField(
            model_name='eamatch',
            name='match_type',
            field=models.CharField(choices=[('friendlyMatch', 'Amistoso'), ('leagueMatch', 'Liga Online'), ('playoffMatch', 'Playoff')], default='friendlyMatch', max_length=20, verbose_name='tipo de partida'),
        ),
        migrations.AddIndex(
            model_name='eamatch',
            index=models.Index(fields=['validation_status'], name='ea_integrat_validat_b9051b_idx'),
        ),
        migrations.AddField(
            model_name='matchvalidationlog',
            name='ea_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='ea_integration.eamatch', verbose_name='partida EA'),
        ),
        migrations.AddIndex(
            model_name='matchvalidationlog',
            index=models.Index(fields=['ea_match', '-created_at'], name='ea_integrat_ea_matc_aadfc0_idx'),
        ),
        migrations.AddIndex(
            model_name='matchvalidationlog',
            index=models.Index(fields=['validation_type'], name='ea_integrat_validat_cae965_idx'),
        ),
        migrations.AddIndex(
            model_name='matchvalidationlog',
            index=models.Index(fields=['severity'], name='ea_integrat_severit_bb49e3_idx'),
        ),
    ]
