# Generated by Django 5.0.14 on 2026-06-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea_integration', '0003_eaclubalias'),
        ('fnc_matches', '0010_match_irregularity_confirmation_fields'),
        ('fnc_teams', '0005_add_commission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eaclub',
            name='team',
            field=models.OneToOneField(blank=True, help_text='Time da PRO ELEVEN vinculado a este clube EA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ea_club', to='fnc_teams.team', verbose_name='time interno'),
        ),
        migrations.AlterField(
            model_name='eamatch',
            name='linked_match',
            field=models.OneToOneField(blank=True, help_text='Match do campeonato PRO ELEVEN vinculado a esta partida EA. Preenchido automaticamente quando o sistema detecta correspondência.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ea_match', to='fnc_matches.match', verbose_name='partida interna vinculada'),
        ),
        migrations.AlterField(
            model_name='matchvalidationlog',
            name='validation_type',
            field=models.CharField(choices=[('team_name_mismatch', 'Nome do time divergente'), ('team_not_registered', 'Time não cadastrado no sistema'), ('player_not_in_roster', 'Jogador não pertence ao elenco'), ('gamertag_mismatch', 'Gamertag irregular ou divergente'), ('stats_anomaly', 'Estatísticas incompatíveis'), ('incomplete_data', 'Dados incompletos na partida'), ('unexpected_team', 'Time inesperado (não era o adversário esperado)'), ('score_mismatch', 'Placar não confere com soma de gols dos jogadores'), ('no_matching_fixture', 'Nenhuma partida agendada encontrada'), ('potential_disconnect_override', 'Possível vitória automática por quit/desconexão')], max_length=30, verbose_name='tipo de validação'),
        ),
    ]
