# Generated by Django 5.0.14 on 2026-06-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea_integration', '0004_alter_eaclub_team_alter_eamatch_linked_match_and_more'),
        ('fnc_matches', '0011_card_source_goal_source'),
        ('fnc_teams', '0005_add_commission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eaclub',
            name='team',
            field=models.OneToOneField(blank=True, help_text='Time da FDT ARENA vinculado a este clube EA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ea_club', to='fnc_teams.team', verbose_name='time interno'),
        ),
        migrations.AlterField(
            model_name='eamatch',
            name='linked_match',
            field=models.OneToOneField(blank=True, help_text='Match do campeonato FDT ARENA vinculado a esta partida EA. Preenchido automaticamente quando o sistema detecta correspondência.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ea_match', to='fnc_matches.match', verbose_name='partida interna vinculada'),
        ),
    ]
