# Generated by Django 5.0.14 on 2026-02-03 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('schema', models.CharField(choices=[('4-4-2', '4-4-2'), ('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('4-1-2-1-2', '4-1-2-1-2'), ('4-3-1-2', '4-3-1-2'), ('3-5-2', '3-5-2'), ('3-4-3', '3-4-3'), ('5-3-2', '5-3-2'), ('5-4-1', '5-4-1'), ('4-1-4-1', '4-1-4-1'), ('4-3-2-1', '4-3-2-1'), ('4-4-1-1', '4-4-1-1'), ('3-4-2-1', '3-4-2-1')], max_length=20, verbose_name='esquema')),
                ('is_default', models.BooleanField(default=False, verbose_name='padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'formação',
                'verbose_name_plural': 'formações',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome do time')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='sigla')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='logo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('foundation_date', models.DateField(auto_now_add=True, verbose_name='data de fundação')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'time',
                'verbose_name_plural': 'times',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceito'), ('DECLINED', 'Recusado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
            ],
            options={
                'verbose_name': 'convite',
                'verbose_name_plural': 'convites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Dono'), ('CAPTAIN', 'Capitão'), ('PLAYER', 'Jogador')], default='PLAYER', max_length=10, verbose_name='função')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='entrou em')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='saiu em')),
            ],
            options={
                'verbose_name': 'membro do time',
                'verbose_name_plural': 'membros do time',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='FormationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=5, verbose_name='posição')),
                ('x_position', models.FloatField(verbose_name='posição X')),
                ('y_position', models.FloatField(verbose_name='posição Y')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='fnc_teams.formation', verbose_name='formação')),
            ],
            options={
                'verbose_name': 'posição na formação',
                'verbose_name_plural': 'posições na formação',
            },
        ),
    ]
