# Generated by Django 5.0.14 on 2026-02-03 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fnc_teams', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formationposition',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.playerprofile', verbose_name='jogador'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='formation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='fnc_teams.team', verbose_name='time'),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='convidado por'),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.playerprofile', verbose_name='jogador'),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='fnc_teams.team', verbose_name='time'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.playerprofile', verbose_name='jogador'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fnc_teams.team', verbose_name='time'),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', through='fnc_teams.TeamMembership', to='users.playerprofile', verbose_name='jogadores'),
        ),
        migrations.AlterUniqueTogether(
            name='formationposition',
            unique_together={('formation', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'player')},
        ),
    ]
