# Generated by Django 5.0.14 on 2026-03-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_teams', '0002_initial'),
        ('users', '0003_alter_user_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Recusado')], default='PENDING', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='solicitado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolvido em')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='users.playerprofile', verbose_name='jogador')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='resolvido por')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'solicitação de saída',
                'verbose_name_plural': 'solicitações de saída',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='teamleaverequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('team', 'player'), name='unique_pending_leave_request'),
        ),
    ]
