# Generated by Django 5.0.14 on 2026-04-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_teams', '0003_add_teamleaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lineup_visual_preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='preferências visuais da escalação'),
        ),
    ]
