# Generated by Django 5.0.14 on 2026-03-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fnc_championships', '0005_alter_championshipenrollment_payment_status_and_more'),
        ('fnc_teams', '0003_add_teamleaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('provider', models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago')], default='MERCADO_PAGO', max_length=30, verbose_name='provedor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('FAILED', 'Falhou'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20, verbose_name='status')),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID no gateway')),
                ('gateway_external_reference', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='referencia externa')),
                ('pix_qr_code_text', models.TextField(blank=True, verbose_name='codigo pix copia e cola')),
                ('pix_qr_code_base64', models.TextField(blank=True, verbose_name='qr code pix em base64')),
                ('ticket_url', models.URLField(blank=True, verbose_name='URL do ticket')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('webhook_last_payload', models.JSONField(blank=True, null=True, verbose_name='ultimo payload de webhook')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='resposta bruta do gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fnc_championships.championship', verbose_name='campeonato')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='fnc_championships.championshipenrollment', verbose_name='inscricao')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fnc_teams.team', verbose_name='time')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago')], default='MERCADO_PAGO', max_length=30, verbose_name='provedor')),
                ('event_type', models.CharField(max_length=100, verbose_name='tipo do evento')),
                ('gateway_event_id', models.CharField(max_length=255, unique=True, verbose_name='ID do evento no gateway')),
                ('payload', models.JSONField(verbose_name='payload')),
                ('processed', models.BooleanField(default=False, verbose_name='processado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
                ('last_error', models.TextField(blank=True, verbose_name='ultimo erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fnc_payments.payment', verbose_name='pagamento')),
            ],
            options={
                'verbose_name': 'evento de pagamento',
                'verbose_name_plural': 'eventos de pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'provider'], name='fnc_payment_status_ef5656_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['team', 'championship'], name='fnc_payment_team_id_2548e3_idx'),
        ),
    ]
