# Generated by Django 5.0.14 on 2026-03-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('ASAAS', 'Asaas'), ('MERCADO_PAGO', 'Mercado Pago')], default='ASAAS', max_length=30, verbose_name='provedor'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider',
            field=models.CharField(choices=[('ASAAS', 'Asaas'), ('MERCADO_PAGO', 'Mercado Pago')], default='ASAAS', max_length=30, verbose_name='provedor'),
        ),
    ]
