# Generated by Django 5.0.14 on 2026-03-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnc_payments', '0002_asaas_provider_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago'), ('ASAAS', 'Asaas')], default='MERCADO_PAGO', max_length=30, verbose_name='provedor'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider',
            field=models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago'), ('ASAAS', 'Asaas')], default='ASAAS', max_length=30, verbose_name='provedor'),
        ),
    ]
