# Generated by Django 5.0.14 on 2026-02-03 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=150, verbose_name='nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='sobrenome')),
                ('user_type', models.CharField(choices=[('PLAYER', 'Jogador'), ('TEAM_OWNER', 'Dono de Time'), ('ADMIN', 'Administrador')], default='PLAYER', max_length=20, verbose_name='tipo de usuário')),
                ('platform', models.CharField(choices=[('PS', 'PlayStation'), ('XBOX', 'Xbox'), ('PC', 'PC')], max_length=10, verbose_name='plataforma')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='último login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='nome do jogador')),
                ('gamer_tag', models.CharField(max_length=100, verbose_name='gamer tag')),
                ('shirt_number', models.PositiveIntegerField(verbose_name='número da camisa')),
                ('primary_position', models.CharField(choices=[('GK', 'Goleiro'), ('CB', 'Zagueiro Central'), ('LB', 'Lateral Esquerdo'), ('RB', 'Lateral Direito'), ('LWB', 'Ala Esquerdo'), ('RWB', 'Ala Direito'), ('CDM', 'Volante'), ('CM', 'Meio-Campo Central'), ('CAM', 'Meia Atacante'), ('LM', 'Meio-Campo Esquerdo'), ('RM', 'Meio-Campo Direito'), ('LW', 'Ponta Esquerda'), ('RW', 'Ponta Direita'), ('ST', 'Atacante'), ('CF', 'Centro-Avante')], max_length=5, verbose_name='posição primária')),
                ('secondary_position', models.CharField(blank=True, choices=[('GK', 'Goleiro'), ('CB', 'Zagueiro Central'), ('LB', 'Lateral Esquerdo'), ('RB', 'Lateral Direito'), ('LWB', 'Ala Esquerdo'), ('RWB', 'Ala Direito'), ('CDM', 'Volante'), ('CM', 'Meio-Campo Central'), ('CAM', 'Meia Atacante'), ('LM', 'Meio-Campo Esquerdo'), ('RM', 'Meio-Campo Direito'), ('LW', 'Ponta Esquerda'), ('RW', 'Ponta Direita'), ('ST', 'Atacante'), ('CF', 'Centro-Avante')], max_length=5, null=True, verbose_name='posição secundária')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='whatsapp')),
                ('country', models.CharField(max_length=100, verbose_name='país')),
                ('language', models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês')], default='pt-br', max_length=10, verbose_name='idioma')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil de jogador',
                'verbose_name_plural': 'perfis de jogadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='owner_avatars/', verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil de dono de time',
                'verbose_name_plural': 'perfis de donos de time',
                'ordering': ['-created_at'],
            },
        ),
    ]
