# Generated by Django 5.0.14 on 2026-02-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='gamer_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='gamer tag'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nome do jogador'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='primary_position',
            field=models.CharField(blank=True, choices=[('GK', 'Goleiro'), ('CB', 'Zagueiro Central'), ('LB', 'Lateral Esquerdo'), ('RB', 'Lateral Direito'), ('LWB', 'Ala Esquerdo'), ('RWB', 'Ala Direito'), ('CDM', 'Volante'), ('CM', 'Meio-Campo Central'), ('CAM', 'Meia Atacante'), ('LM', 'Meio-Campo Esquerdo'), ('RM', 'Meio-Campo Direito'), ('LW', 'Ponta Esquerda'), ('RW', 'Ponta Direita'), ('ST', 'Atacante'), ('CF', 'Centro-Avante')], max_length=5, null=True, verbose_name='posição primária'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='shirt_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='número da camisa'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='whatsapp'),
        ),
    ]
