# Generated by Django 5.0.14 on 2026-02-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_playerprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PLAYER', 'Jogador'), ('TEAM_OWNER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Administrador')], default='PLAYER', max_length=20, verbose_name='tipo de usuário'),
        ),
    ]
