# Generated by Django 5.0.14 on 2026-04-01 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_users(apps, schema_editor):
    """
    Marca todos os usuários existentes como verificados.
    Novos usuários criados após esta migration terão is_email_verified=False.
    """
    User = apps.get_model('users', 'User')
    User.objects.filter(is_active=True).update(is_email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_cpf_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='email verificado'),
        ),
        # Grandfathear usuários existentes
        migrations.RunPython(
            grandfather_existing_users,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='código')),
                ('code_type', models.CharField(choices=[('EMAIL_VERIFICATION', 'Verificação de Email'), ('PASSWORD_RESET', 'Redefinição de Senha')], max_length=20, verbose_name='tipo de código')),
                ('is_used', models.BooleanField(default=False, verbose_name='utilizado')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='tentativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'código de verificação',
                'verbose_name_plural': 'códigos de verificação',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'code_type', '-created_at'], name='users_verif_user_id_597f79_idx'), models.Index(fields=['code', 'code_type'], name='users_verif_code_cfc333_idx')],
            },
        ),
    ]
